### ISSUE TITLE
Shimming; Space Mouse not reacting...

### ISSUE THREAD

**Issue by Matele0** [RoboPhred/shipbreaker-sixaxis#1]
[LogOutput.log](https://github.com/RoboPhred/shipbreaker-sixaxis/files/5924652/LogOutput.log)

Cannot get the SpaceMouse running. (No reaction at all)

Any Hints?

**Comment by RoboPhred** [comment]
Can you give me the vendor and product ID of your particular space mouse?  It is probably one that isn't listed on their website.

You can find it by going to https://gamepad-tester.com.  Move your spacemouse around and find the entry that shows changes when you do.  The site should show a Vendor ID and Product ID.

You can test if you got the right one by adding it into the config file of the mod:
https://github.com/RoboPhred/shipbreaker-sixaxis/blob/master/device-configs/3DConnexion.yml

Just edit this file in the mod's folder and insert your vendor and product ID as a new entry.  Be sure to get the syntax correct, it is sensitive to how many spaces are before the item.

**Comment by Matele0** [comment]
Hello!
 
Thank you for your response!
Thanks to your hints I found that a “C” is missing in the configuration file.

  - # Space Navigator (notebook)
    vendorId: 0x046D
    productId: 0xC628                                   <-------------------

 
Looking at the log files it seems that now everything should be fine.
Sadly there is still no moving in the game when I try  to control it with the space mouse. (The space mouse works, I use it with Fusion 360)

LogOutput.log :
[Message:   BepInEx] BepInEx 5.4.9.0 - Shipbreaker
[Info   :   BepInEx] Running under Unity v2019.4.10.5444019
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 1 plugins to load
[Info   :   BepInEx] Loading [Six Axis Joystick support for Shipbreaker 1.1.2.0]
[Message:   BepInEx] Chainloader startup complete

log.txt: DateTime=2021-04-23T12:44:42Z 
Patch succeeded

DateTime=2021-04-23T12:44:42Z ConfigFolder=D:\Programme\Steam\steamapps\common\Hardspace Shipbreaker\BepInEx\plugins\SixAxis\device-configs 
Loading input configuration

DateTime=2021-04-23T12:44:43Z 
Loaded 1 input configurations.

DateTime=2021-04-23T12:44:43Z VendorId=46D ProductId=C628 ConfigFile=3DConnexion.yml 
Found input mapping for device 46D:C628




Do you have any additional hints  for me?

Thank you, 
Martin

**Comment by RoboPhred** [comment]
I just tried the mod against the most recent version of the game using a SpacePilot Pro and didn't have any trouble with it.

If you want, I can help you debug this further if you contact me in Discord under `@RoboPhred#7375`, either directly or in the #modding-discussion channel on the Hardspace Shipbreaker server.

**Comment by Matele0** [comment]
Just downloaded the 0.4.0 update. Now all works like a charm! 
Thank you,
Martin
